version: "3.7"
services:
  invidious-db:
    image: postgres:14
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: invidious
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  invidious:
    image: quay.io/invidious/invidious:latest
    environment:
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
      COMPANION_SECRET: "${COMPANION_SECRET}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      HMAC_KEY: "${INVIDIOUS_HMAC_KEY}"
      DOMAIN: "yt.cudasystems.net"
    ports:
      - "3000:3000"
    volumes:
      - ./config/config.yml:/config/config.yml:ro
    depends_on:
      - invidious-db

volumes:
  db-data:
