version: "3.8"

services:
  invidious-db:
    image: postgres:15
    container_name: invidious-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: invidious
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - invidious-db-data:/var/lib/postgresql/data

  companion:
    image: quay.io/invidious/invidious-companion:latest
    container_name: invidious-companion
    restart: unless-stopped
    environment:
      # secret used to secure companion <-> invidious
      SERVER_SECRET_KEY: "${COMPANION_SECRET}"
    ports:
      - "127.0.0.1:8282:8282"   # localhost only
    volumes:
      - companion-cache:/var/tmp/youtubei.js

  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    restart: unless-stopped
    depends_on:
      - invidious-db
      - companion
    ports:
      - "127.0.0.1:3000:3000"   # bind to localhost only
    volumes:
      - ./config.yml:/invidious/config/config.yml:ro   # optional, if you maintain a config file in repo
    environment:
      # Minimal overrides; the real configuration lives in config.yml or above envs
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
      COMPANION_SECRET: "${COMPANION_SECRET}"
      # If you prefer to inline the config instead of mounting config.yml, you can set INVIDIOUS_CONFIG here
      # INVIDIOUS_CONFIG: |
      #    db:
      #      dbname: invidious
      #      user: invidious
      #      password: "${POSTGRES_PASSWORD}"
      #      host: invidious-db
      #    domain: "yt.cudasystems.net"
      #    https_only: false
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:3000/api/v1/trending || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  invidious-db-data:
  companion-cache:
