version: "3.7"

services:
  invidious-db:
    image: postgres:15
    container_name: invidious-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    depends_on:
      - invidious-db
    environment:
      INVIDIOUS_DB_HOST: invidious-db
      INVIDIOUS_DB_USER: ${POSTGRES_USER}
      INVIDIOUS_DB_PASSWORD: ${POSTGRES_PASSWORD}
      INVIDIOUS_DB_NAME: ${POSTGRES_DB}

      # Secrets pulled from Coolify env manager
      INVIDIOUS_HMAC_KEY: ${INVIDIOUS_HMAC_KEY}
      INVIDIOUS_COOKIE_SECRET: ${INVIDIOUS_COOKIE_SECRET}
      INVIDIOUS_YT_API_KEY: ${YOUTUBE_API_KEY}

    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
