version: "3.9"

services:
  invidious-db:
    image: postgres:14
    container_name: invidious-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: invidious
    volumes:
      - pgdata:/var/lib/postgresql/data

  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    restart: always
    depends_on:
      - invidious-db
    environment:
      INVIDIOUS_CONFIG: /invidious/config/config.yml
      INVIDIOUS_DB_HOST: invidious-db
      INVIDIOUS_DB_NAME: invidious
      INVIDIOUS_DB_USER: ${POSTGRES_USER}
      INVIDIOUS_DB_PASS: ${POSTGRES_PASSWORD}
      YT_API_KEY: ${YT_API_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      INVIDIOUS_DOMAIN: ${INVIDIOUS_DOMAIN}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./config:/invidious/config

volumes:
  pgdata:
