version: "3.8"
services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
          - private_url: "http://companion:8282/companion"
        invidious_companion_key: "${COMPANION_KEY}"
        hmac_key: "${HMAC_KEY}"
        domain: "yt.cudasystems.net"
        https_only: true
        external_port: 443
        use_pubsub_feeds: true
    depends_on:
      - invidious-db
      - companion

  companion:
    image: quay.io/invidious/invidious-companion:latest
    restart: unless-stopped
    environment:
      - SERVER_SECRET_KEY=${COMPANION_KEY}
    ports:
      - "127.0.0.1:8282:8282"
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    cap_drop:
      - ALL
    read_only: true

  invidious-db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal

volumes:
  postgresdata:
  companioncache:
